LIB := zsvanalysis
#TEST := test.exe
DICT := 1

USERCXXFLAGS += $(ROOT_CFLAGS) $(BOOST_CFLAGS)
USERLDFLAGS += $(ROOT_LDFLAGS) -lra

#all: ../lib/libdra.so test.exe dra_local

include ../Makefile.rules
