LIB := zsvanalysis
#TEST := test.exe
DICT := 1

USERCXXFLAGS += $(ROOT_CFLAGS) $(BOOST_CFLAGS)
USERLDFLAGS += $(ROOT_LDFLAGS) -lra

BIN:=plot_reco plot_me
#plot_gen plot_single_efficiency

include ../Makefile.rules
